// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Register() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><link href=\"/public/css/output.css\" rel=\"stylesheet\"><script src=\"/public/preline/dist/preline.js\"></script><link href=\"/public/css/register/main.css\" rel=\"stylesheet\"><script src=\"/public/js/htmx/htmx.min.js\"></script></head><body class=\"\"><div class=\"h-screen grid grid-cols-1 md:grid-cols-3 gap-4\"><div class=\"hidden md:block hero-pattern overflow-hidden\"><div><img src=\"/public/images/register/logo.png\" class=\"max-w-none w-60 h-auto\" alt=\"Edresco logo\"><p class=\"pl-6 text-white\">Learning Today, Leading Tomorrow</p></div></div><div class=\"col-span-2 p-2 overflow-scroll\"><h1 class=\"text-3xl mb-2 mt-2\">Register</h1><p class=\"mb-4\">Please fill your details</p><div class=\"grid grid-cols-3 gap-4\"><div class=\"col-span-2\" id=\"form-space\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></div><script src=\"https://unpkg.com/validator@latest/validator.min.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
